### ISSUE TITLE
Working on "Select project type" pop-up menu

### ISSUE THREAD

**Issue by keerthana054** [TomerFi/tomfi-archetypes#80]
### What did you have in mind?

I'm thinking of making the pop-up menu more engaging and user-friendly.

### Are you trying to fix a problem?

![image](https://user-images.githubusercontent.com/91015385/184683781-ccf9109d-a52a-4bb9-a080-eb8ffcacf52a.png)

Enhancing already available pop-up menu.

### Any lead on how this feature can be implemented?

This can be implemented by using CSS.

**Comment by TomerFi** [comment]
Sounds awesome!

**Comment by keerthana054** [comment]
> Sounds awesome!

I have few doubts sir! How can I contact you in other modes?!

**Comment by TomerFi** [comment]
My gmail is public in my profile, please free to use it.
:-)
